In [1]:
import os

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import ShuffleSplit
from tqdm.auto import tqdm
import spacy

nlp = spacy.load('en_core_web_sm')
from IdentifyBlogger.PhraseEncoder import PhraseEncoder

In [2]:
import torch
from torch import nn

In [8]:
y_pred = torch.rand(4, 5)
labels = torch.tensor([0,1,2,4]).view(-1)
y_pred, labels.shape

(tensor([[0.6763, 0.7213, 0.6561, 0.0380, 0.0289],
         [0.6761, 0.7473, 0.0974, 0.1709, 0.4837],
         [0.2725, 0.6540, 0.5003, 0.9832, 0.6606],
         [0.0418, 0.9127, 0.1474, 0.6326, 0.9608]]),
 torch.Size([4]))

In [15]:
y_pred.detach().argmax(1)

tensor([1, 1, 3, 4])

In [13]:
l = nn.CrossEntropyLoss()

In [14]:
l(y_pred, labels)

tensor(1.4359)

In [11]:
act = nn.Softmax(dim=1)

In [12]:
act(y_pred)

tensor([[0.2452, 0.2565, 0.2403, 0.1295, 0.1284],
        [0.2461, 0.2643, 0.1380, 0.1485, 0.2031],
        [0.1383, 0.2025, 0.1737, 0.2815, 0.2039],
        [0.1135, 0.2711, 0.1261, 0.2049, 0.2845]])

{{badge}}

In [3]:
d = pd.DataFrame({"a": [1,2,3], "b": [4,5,6], "c": [7,8,9]})

In [4]:
for i, j in zip(*d.values):
    print(f"{i} {j}")

ValueError: too many values to unpack (expected 2)

In [5]:
d_t = d.applymap(torch.tensor)

In [6]:
d_t.iloc[0].to_dict()

{'a': tensor(1), 'b': tensor(4), 'c': tensor(7)}

In [8]:
DATA_PATH = "D:/data/blogtext/blogtext.csv"
TEST_SIZE = 0.1

In [158]:
d["d"] = [8,5,2]

In [160]:
len(d.to_dict()), d.to_dict()

(4,
 {'a': {0: 1, 1: 2, 2: 3},
  'b': {0: 4, 1: 5, 2: 6},
  'c': {0: 7, 1: 8, 2: 9},
  'd': {0: 8, 1: 5, 2: 2}})

In [9]:
data = pd.read_csv(DATA_PATH)
data.head()

id gender  age              topic      sign          date  \
0  2059027   male   15            Student       Leo   14,May,2004   
1  2059027   male   15            Student       Leo   13,May,2004   
2  2059027   male   15            Student       Leo   12,May,2004   
3  2059027   male   15            Student       Leo   12,May,2004   
4  3581210   male   33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  
0             Info has been found (+/- 100 pages,...  
1             These are the team members:   Drewe...  
2             In het kader van kernfusie op aarde...  
3                   testing!!!  testing!!!            
4               Thanks to Yahoo!'s Toolbar I can ...

In [161]:
pd.read_csv(DATA_PATH).head(1000).to_csv("./temp_data")

In [4]:
data = data.drop(["date"], axis=1)
data.head()

id gender  age              topic      sign  \
0  2059027   male   15            Student       Leo   
1  2059027   male   15            Student       Leo   
2  2059027   male   15            Student       Leo   
3  2059027   male   15            Student       Leo   
4  3581210   male   33  InvestmentBanking  Aquarius   

                                                text  
0             Info has been found (+/- 100 pages,...  
1             These are the team members:   Drewe...  
2             In het kader van kernfusie op aarde...  
3                   testing!!!  testing!!!            
4               Thanks to Yahoo!'s Toolbar I can ...

In [139]:
B = [d_t.iloc[0].to_dict()] * 3
B

[{'a': tensor(1), 'b': tensor(4)},
 {'a': tensor(1), 'b': tensor(4)},
 {'a': tensor(1), 'b': tensor(4)}]

In [145]:
a, b = zip(*[e.values() for e in B])
a

(tensor(1), tensor(1), tensor(1))

In [12]:
data["text_length"] = data["text"].apply(len)
data.head()

id gender  age              topic      sign          date  \
0  2059027   male   15            Student       Leo   14,May,2004   
1  2059027   male   15            Student       Leo   13,May,2004   
2  2059027   male   15            Student       Leo   12,May,2004   
3  2059027   male   15            Student       Leo   12,May,2004   
4  3581210   male   33  InvestmentBanking  Aquarius  11,June,2004   

                                                text  text_length  
0             Info has been found (+/- 100 pages,...          157  
1             These are the team members:   Drewe...          181  
2             In het kader van kernfusie op aarde...        25467  
3                   testing!!!  testing!!!                     43  
4               Thanks to Yahoo!'s Toolbar I can ...          402

In [13]:
s = data.sort_values(["text_length"])

In [172]:
s.head(90)

id  gender  age                 topic         sign  \
8877    4256671    male   15                indUnk        Virgo   
375793  3418052  female   26     Sports-Recreation  Sagittarius   
396741  3546623  female   42                indUnk        Libra   
651904   235374    male   27            Technology       Taurus   
651906   235374    male   27            Technology       Taurus   
...         ...     ...  ...                   ...          ...   
620557   239860    male   25                indUnk          Leo   
266523  1842049  female   24                indUnk     Aquarius   
280195  4116243  female   24         Manufacturing  Sagittarius   
359725  3918548    male   33                indUnk    Capricorn   
345857  2283987  female   23  Communications-Media    Capricorn   

                    date     text  text_length  
8877      23,August,2004                     4  
375793       20,May,2004                     4  
396741    01,August,2004                     4  
651904      17,June,2004                     4  
651906      14,June,2004                     4  
...                  ...      ...          ...  
620557  17,February,2002     uh?             7  
266523       26,May,2004                     7  
280195    07,August,2004                     7  
359725    09,August,2004                     7  
345857     29,April,2004                     7  

[90 rows x 8 columns]

In [14]:
len(s)

681284

In [126]:
d_t.values, d_t

(array([[tensor(1), tensor(4)],
        [tensor(2), tensor(5)],
        [tensor(3), tensor(6)]], dtype=object),
            a          b
 0  tensor(1)  tensor(4)
 1  tensor(2)  tensor(5)
 2  tensor(3)  tensor(6))

In [131]:
a, b = zip(*d_t.values)
a

(tensor(1), tensor(2), tensor(3))

In [15]:
enc = PhraseEncoder()
enc.load_vocabulary("./utils")

In [16]:
t = s["text"].apply(enc.encode_phrase)

In [22]:
l = t.apply(len)

In [23]:
sum(l == 0)

3296

In [45]:
phrase = data["text"].iloc[0]
phrase

'           Info has been found (+/- 100 pages, and 4.5 MB of .pdf files) Now i have to wait untill our team leader has processed it and learns html.         '

In [88]:
def _lookup_enc(token):
    t = token.text
    return enc.vocabulary["xxunk"] if t not in enc.vocabulary.keys() else enc.vocabulary[t]

In [89]:
def _lookup_enc2(token):
#     t = token.text
    return enc.vocabulary["xxunk"] if t not in enc.vocabulary.keys() else enc.vocabulary[t]

In [73]:
n = 1000
phrase = re.sub('\W+', ' ', phrase.lower())
phrase = phrase if not phrase.startswith(' ') else phrase[1:]

In [74]:
%%time
for _ in range(n):
    e1 = [_lookup_enc(token) for token in enc.nlp(phrase, disable=['parser', 'tagger', 'ner'])]

Wall time: 47 ms


In [120]:
%%time
e2 = [*map(_lookup_enc2, (phrase * n).split())]

Wall time: 19.5 ms


In [121]:
%%time
for _ in range(n):
    e3 = [*map(_lookup_enc2, phrase.split())]

Wall time: 12 ms


In [79]:
e1 == list(e2)

True

In [102]:
12 / 47

0.2553191489361702

In [117]:
phrase * 2

'info has been found 100 pages and 4 5 mb of pdf files now i have to wait untill our team leader has processed it and learns html info has been found 100 pages and 4 5 mb of pdf files now i have to wait untill our team leader has processed it and learns html '

In [19]:
import re

# re.sub('[^A-Za-z0-9]+', ' ', t)
t1 = re.sub('\W+',' ', t)
t1 = t1 if not t1.startswith(' ') else t1[1:]
t1

'info has been found 100 pages and 4 5 mb of pdf files now i have to wait untill our team leader has processed it and learns html '

In [18]:
tokens = nlp(t1, disable=['parser', 'tagger', 'ner'])
[token.text for token in tokens]

[' ',
 'info',
 'has',
 'been',
 'found',
 '100',
 'pages',
 'and',
 '4',
 '5',
 'mb',
 'of',
 'pdf',
 'files',
 'now',
 'i',
 'have',
 'to',
 'wait',
 'untill',
 'our',
 'team',
 'leader',
 'has',
 'processed',
 'it',
 'and',
 'learns',
 'html']

In [154]:
5 % 2

1

In [58]:
ids = data["id"].unique()
np.random.shuffle(ids)
print(ids)

[3922244 4065452 4176448 ... 4220141 3944784 3723550]


In [80]:
d = {"a": 1, "b":2}

for k, v in d.items():
    print(f"{k} {v}")

a 1
b 2


In [66]:
test_bloggers = ids[:int(TEST_SIZE*ids.size)]
train_bloggers = ids[test_bloggers.size:]

In [72]:
test_ids = list(data[data["id"].isin(test_bloggers)].index)
train_ids = list(data[data["id"].isin(train_bloggers)].index)

In [85]:
data["age"].iloc[test_ids].max()

48

In [74]:
len(train_ids)

618774

In [78]:
for i, v in enumerate(sorted(list(data["topic"].unique()))):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [21]:
not_monothematic = 0

for i in tqdm(data["id"].unique()):
    if len(data[data["id"] == i]["topic"].unique()) != 1:
        not_monothematic += 1
        
print(not_monothematic)


0


In [34]:
concated_targets = data.loc[:, data.columns != "text"].copy()
concated_targets = concated_targets.drop_duplicates().sample(frac=1)# .reset_index(drop=True)
concated_targets["target"] = concated_targets.apply(lambda x: f'{x["gender"]}.{x["age"]}.{x["topic"]}.{x["sign"]}', axis=1)
concated_targets = concated_targets[["id", "target"]]
concated_targets.head()

id                     target
52425   2153234    male.27.Religion.Pisces
481363  1807459  male.25.Education.Scorpio
472108  3509908     female.16.indUnk.Aries
674508   445168         male.25.indUnk.Leo
444043  1901727     female.41.Arts.Scorpio

In [35]:
concated_targets.iloc[0]

id                        2153234
target    male.27.Religion.Pisces
Name: 52425, dtype: object

In [44]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.8)
ss = ShuffleSplit(n_splits=1, test_size=0.8)

In [47]:
ss.split(concated_targets["id"])

<generator object BaseShuffleSplit.split at 0x00000294087DE6C8>

In [39]:
len(concated_targets["target"].unique())

5239

In [34]:
concated_targets.apply(lambda x: 1, axis=1)

0         1
4         1
74        1
95        1
97        1
         ..
681004    1
681025    1
681141    1
681156    1
681161    1
Length: 19320, dtype: int64

In [33]:
len(concated_targets) == len(concated_targets["id"].unique())

True

In [18]:
data[data["id"] == 3581210]["topic"].unique()

array(['InvestmentBanking'], dtype=object)

In [7]:
data_t = data[["id", "topic"]]

In [14]:
len(data["id"].unique())

19320

In [12]:
data_t.groupby(["id"]).unique()

AttributeError: 'DataFrameGroupBy' object has no attribute 'unique'